### ISSUE TITLE
Just need a small help

### ISSUE THREAD

**Issue by Small-pp** [stephenbradshaw/vulnserver#5]
I want to run this in my localhost so I have to change the code but i can't program in c so please tell me what to change in it so I can run in localhost

**Comment by stephenbradshaw** [comment]
Untested, but changing [line 83 in vulnserver.c](https://github.com/stephenbradshaw/vulnserver/blob/master/vulnserver.c#L83) to specify the localhost address in the first parameter to [getaddrinfo](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo) should do the job. Given that you will need to recompile to do this however, you probably will need to gain at least basic C proficiency to do this.

It will probably be easier to just use a local firewall to prevent remote access if thats what you're worried about.

**Comment by Small-pp** [comment]
Thank you for the help

**Comment by Small-pp** [comment]
Hey as i said i want to run it in local host and i can't program in c . So can you please tell me what to rewrite in line 83 and sorry for my bad English :(

And i am new in this field so i don't know much :(

It will be great if you say what will be the line after changing :)
